## ---- data source
task_name: 'custom_task'
given_dir: null
cases: null
parallel: false
skip_if_processed_recently: false
check_time: 1674417578

## ---- path -- absolute path or relative to `pybullet_planning`
given_path: null
camera_kwargs: null

## default shot is focusing on the braiser
#camera_point: null
#target_point: null

## wide shot from the side
camera_point: [4.5, 2.5, 3]
target_point: [0, 2.5, 0]

## ---- control
preview_scene: false
step_by_step: false
use_gym: false
auto_play: true
verbose: false

## ---- visual
width: 1440
height: 1120
fx: 60
time_step: 0.05
#camera_kwargs: null
camera_movement: null
light_conf: null
make_robot_and_links_transparent: false

## ---- purposes
check_collisions: false
cfree_range: 0.1
visualize_collisions: false
evaluate_quality: false

## ---- outputs
save_jpg: false
save_composed_jpg: false
save_gif: false
save_animation_json: false
save_mp4: false
mp4_side_view: false
mp4_top_view: false